# lable encoding

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame({"name":["sql", "python", "excel", "pandas", "ml", "dl"]})

In [6]:
df

     name
0     sql
1  python
2   excel
3  pandas
4      ml
5      dl

In [7]:
from sklearn.preprocessing import LabelEncoder

# sklearn library h pandas numpy ki trha / jise import krna ho

In [8]:
# ab ise ek variable me store kr do

le = LabelEncoder()

In [19]:
# fit transform ki help se jo text vala (name) vala coulmn 
# hota h use no. me transfer krta h 

le.fit_transform(df["name"])

array([5, 4, 1, 3, 2, 0])

In [20]:
# ab ise bhi ek variable me store kr do 

df["en_name"] = le.fit_transform(df["name"])

In [16]:
df

     name  en_name
0     sql        5
1  python        4
2   excel        1
3  pandas        3
4      ml        2
5      dl        0

In [17]:
new_data = df

In [18]:
new_data.to_csv("namra.csv",index = False)